server:
  applicationConnectors:
    - type: http
      port: 2890
  adminConnectors:
    - type: http
      port: 2891      
logging:
  level: INFO

# the only required property is resourcePackage, for more config options see below
swagger:
  resourcePackage: edu.qaware.cc.zwitscher