apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-service-dynamic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
