version: "3"
services:
  tle-fetcher:
    image: qaware/tle-fetcher:1.0.0
    depends_on:
      - promtail
      - tempo
    ports:
      - "8080:8080"
    volumes:
      - tle_fetcher_logs:/logs
    networks:
      - default

  sky-map:
    image: qaware/sky-map:1.0.0
    environment:
      - QUARKUS_REST_CLIENT_TLE_FETCHER_URL=http://tle-fetcher:8080
    depends_on:
      - tle-fetcher
      - promtail
      - tempo
    ports:
      - "8088:8088"
    volumes:
      - sky_map_logs:/logs
    networks:
      - default

  grafana:
    image: grafana/grafana:9.5.14
    depends_on:
      - tempo
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards/
    networks:
      - default

  tempo:
    image: grafana/tempo:2.3.0
    command:
      - '-config.file=/etc/tempo.yaml'
    ports:
      - "14268:14268"  # jaeger ingest, Jaeger - Thrift HTTP
      - "14250:14250"  # Jaeger - GRPC
      - "4317:4317"    # OpenTelemetry gRPC
      - "4318:4318"    # OpenTelemetry HTTP
      - "3102:3100"    # tempo
    expose:
      - "4317"
      - "4318"
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/data/tempo
    networks:
      - default

  loki:
    image: grafana/loki:2.9.2
    command:
      - '-config.file=/etc/loki/local-config.yaml'
    volumes:
      - loki_data:/loki
    networks:
      - default

  promtail:
    image: grafana/promtail:2.9.2
    depends_on:
      - loki
    command:
      - '-config.file=/etc/promtail/promtail.yaml'
    volumes:
      - ./promtail:/etc/promtail
      - tle_fetcher_logs:/tle-fetcher-logs
      - sky_map_logs:/sky-map-logs
    networks:
      - default

  mimir:
    image: grafana/mimir:2.9.3
    command: ["-config.file=/etc/mimir.yaml"]
    depends_on:
      - minio
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir.yaml
      - mimir_data:/mimir
      - ./mimir/metrics-activity.log:/var/log/mimir/metrics-activity.log

  minio:
    image: minio/minio:RELEASE.2023-11-15T20-43-25Z
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/mimir && minio server --quiet /data"]
    depends_on:
      - createbuckets
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password123
    volumes:
      - minio_blocks:/data

  createbuckets:
    image: minio/mc
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 root password123;
      
      /usr/bin/mc rm -r --force myminio/mimir-blocks;
      /usr/bin/mc mb myminio/mimir-blocks;
      /usr/bin/mc policy download myminio/mimir-blocks;
      
      /usr/bin/mc rm -r --force myminio/mimir-alertmanager;
      /usr/bin/mc mb myminio/mimir-alertmanager;
      /usr/bin/mc policy download myminio/mimir-alertmanager;
      
      /usr/bin/mc rm -r --force myminio/mimir-ruler;
      /usr/bin/mc mb myminio/mimir-ruler;
      /usr/bin/mc policy download myminio/mimir-ruler;
      exit 0;
      "

  grafana-agent:
    image: grafana/agent:v0.37.4
    entrypoint: grafana-agent run /etc/grafana-agent.river --storage.path=/tmp/data-agent
    environment:
      - AGENT_MODE=flow
    volumes:
      - ./grafana-agent/grafana-agent.river:/etc/grafana-agent.river
      - grafana-agent-data-agent:/tmp/data-agent

volumes:
  tle_fetcher_logs: {}
  sky_map_logs: {}
  grafana_data: {}
  grafana-agent-data-agent: {}
  loki_data: {}
  mimir_data: {}
  minio_blocks: {}
  tempo_data: {}

networks:
  default:
    driver: bridge
