version: "2"

services:
  consul1:
    image: "consul:1.0.1"
    container_name: "consul1"
    hostname: "consul1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "agent -server -ui"
  consul2:
    image: "consul:1.0.1"
    container_name: "consul2"
    hostname: "consul2"
    expose:
      - "8400"
      - "8500"
      - "8600"
    command: "agent -server -join consul1"
    depends_on:
      - consul1
  consul3:
    image: "consul:1.0.1"
    container_name: "consul3"
    hostname: "consul3"
    expose:
      - "8400"
      - "8500"
      - "8600"
    command: "agent -server -join consul1"
    depends_on:
      - consul1
