version: '3'
services:
  book-service:
    build: ./book-service
    image: book-service:1.1.0
    ports:
      - 18080:18080
    networks:
      - cloud-architecture
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul

networks:
  cloud-architecture: