apiVersion: v1
kind: Service
metadata:
  name: helloservice-service
  labels:
    app: helloservice
spec:
  selector:
    app: helloservice
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
