apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: book-application
spec:
  selector:
    matchLabels:
      app: BookServiceApplication
  replicas: 2
  template:
    metadata:
      labels:
        app: BookServiceApplication
    spec:
      containers:
      - name: book-service
        image: book-service:1.0.1
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /admin/info
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /admin/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        env:
        - name: JAVA_OPTS
          value: -Xmx128m
        - name: INFO_APP_NAME
          valueFrom:
            configMapKeyRef:
              name: bool-config
              key: info.app.name
